# Generated by Django 3.2.6 on 2021-08-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(default=0)),
                ('nome', models.CharField(default=0, max_length=60)),
                ('profissão', models.CharField(default=0, max_length=25)),
            ],
        ),
    ]
