# Generated by Django 3.2.6 on 2021-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pessoas_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
    ]
