# Generated by Django 3.2.6 on 2021-08-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoas_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='profissão',
            field=models.CharField(max_length=25),
        ),
    ]
